name: Docker Tests

on: 
  push:
      branches:[main]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    env:
    MIS_TEAM5_URL: ${{secrets.MIS_TEAM5_URL}}
    MIS_TEAM5_USERNAME: ${{secrets.MIS_TEAM5_USERNAME}}
    MIS_TEAM5_PASSWORD: ${{secrets.MIS_TEAM5_PASSWORD}}
    MIS_TEAM5_SCHOOL_ID: ${{secrets.MIS_TEAM5_SCHOOL_ID}}
    VISION_TEAM5_URL: ${{secrets.VISION_TEAM5_SCHOOL_ID}}
    VISION_TEAM5_CUSTOMER_CODE: ${{secrets.VISION_TEAM5_CUSOMTER_CODE}}
    VISION_TEAM5_USERNAME: ${{secrets.VISION_TEAM5_USERNAME}}
    VISION_TEAM5_PASSWORD: ${{secrets.VISION_TEAM5_PASSWORD}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t sdet_framework .

      - name: Run tests in contaiter
        run: docker run --rm -e ENV=$ENV -e MIS_TEAM5_URL=$MIS_TEAM5_URL -e MIS_TEAM5_USERNAME=$MIS_TEAM5_USERNAME -e MIS_TEAM5_PASSWORD=$MIS_TEAM5_PASSWORD -e MIS_TEAM5_SCHOOL_ID=$MIS_TEAM5_SCHOOL_ID -e VISION_TEAM5_URL=$VISION_TEAM5_URL -e VISION_TEAM5_CUSTOMER_CODE=$VISION_TEAM5_CUSTOMER_CODE -e VISION_TEAM5_USERNAME=$VISION_TEAM5_USERNAME -e VISION_TEAM5_PASSWORD=$VISION_TEAM5_PASSWORD -e ENV=Release sdet_framework 