name: Docker Tests

on: 
  push:
      branches: [main]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    environment: RELEASE
    env:
      MIS_RELEASE_URL: ${{secrets.MIS_RELEASE_URL}}
      MIS_RELEASE_USERNAME: ${{secrets.MIS_RELEASE_USERNAME}}
      MIS_RELEASE_PASSWORD: ${{secrets.MIS_RELEASE_PASSWORD}}
      MIS_RELEASE_SCHOOL_ID: ${{secrets.MIS_RELEASE_SCHOOL_ID}}
      VISION_RELEASE_URL: ${{secrets.VISION_RELEASE_URL}}
      VISION_RELEASE_CUSTOMER_CODE: ${{secrets.VISION_RELEASE_CUSOMTER_CODE}}
      VISION_RELEASE_USERNAME: ${{secrets.VISION_RELEASE_USERNAME}}
      VISION_RELEASE_PASSWORD: ${{secrets.VISION_RELEASE_PASSWORD}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t sdet_framework .

      - name: Run tests in container
        run: docker run --rm -e ENV=$ENV -e MIS_RELEASE_URL=$MIS_RELEASE_URL -e MIS_RELEASE_USERNAME=$MIS_RELEASE_USERNAME -e MIS_RELEASE_PASSWORD=$MIS_RELEASE_PASSWORD -e MIS_RELEASE_SCHOOL_ID=$MIS_RELEASE_SCHOOL_ID -e VISION_RELEASE_URL=$VISION_RELEASE_URL -e VISION_RELEASE_CUSTOMER_CODE=$VISION_RELEASE_CUSTOMER_CODE -e VISION_RELEASE_USERNAME=$VISION_RELEASE_USERNAME -e VISION_RELEASE_PASSWORD=$VISION_RELEASE_PASSWORD -e ENV=Release sdet_framework