name: Playwright Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: Team5
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with: 
          python-version: '3.10'
    - run: pip install -r requirements.txt
    - run: playwright install
    - run: pytest -v
      env:
        ENV: Team5
        MIS_TEAM5_URL: ${{ secrets.MIS_TEAM5_URL }}
        MIS_TEAM5_USERNAME: ${{ secrets.MIS_TEAM5_USERNAME }}
        MIS_TEAM5_PASSWORD: ${{ secrets.MIS_TEAM5_PASSWORD }}
        VISION_TEAM5_URL: ${{ secrets.VISION_TEAM5_URL }}
        VISION_TEAM5_USERNAME: ${{ secrets.VISION_TEAM5_USERNAME }}
        VISION_TEAM5_PASSWORD: ${{ secrets.VISION_TEAM5_PASSWORD }}
        VISION_TEAM5_CUSTOMER_CODE: ${{ secrets.VISION_TEAM5_CUSTOMER_CODE }}